### ISSUE TITLE
Agent and Environment Integration

### ISSUE THREAD

**Issue by ctrlnomad** [broadinstitute/AutoTrain#9]
# DQN Agent Integration Into The AutoTrain Environment

TODOs:
 - [ ] implement horizon
 - [ ] conv2d 

What experiments to run?

**Comment by jccaicedo** [comment]
You can remove any dependency that we have with the Cart Pole example. The idea is to replace it with code that works for our problem.

The first experiment to run would be to have the agent successfully interacting with our environment. Let's define success here as running one experiment for 100 episodes with no errors. And let's measure execution time as a reference for future experiments.
